### ISSUE TITLE
Error message for invalid yaml with mani edit command

### ISSUE THREAD

**Issue by NicolasDelahaigue** [alajmo/mani#18]
Hello,

**Is your feature request related to a problem? Please describe.**
When the *mani.yaml* is invalid, there is a `yaml: unmarshal errors` error, the behavior is normal.
But when you do `mani edit` it also print this error and prevents the file from being opened. So the only way to fix the error in the yaml file is to open the file with an editor.

**Describe the solution you'd like**
To always be able to open the mani.yaml file, would it be possible to remove the yaml validity check for the command `mani edit` ?

**Additional context**
N/A

Thanks in advance for your help

**Comment by alajmo** [comment]
I agree, the `mani edit` command should not prevent the main `mani.yaml` config from being opened, I also found some issues with auto-completion when the YAML is invalid, so I'll take a look at fixing those bugs. Thanks for finding the bug!

**Comment by alajmo** [comment]
Close as the new release should fix this.
