### ISSUE TITLE
init with multiple repos with the same name

### ISSUE THREAD

**Issue by stessaris** [alajmo/mani#30]
If there are multiple repos with the same name within different subdirectories, `mani init` creates an invalid `mani.yaml` file where keys appear multiple times within the `projects` object.

A quick solution would be to prepend part of the path to distinguish them in case of repetitions.

**Comment by alajmo** [comment]
Good catch, and seems like a good enough solution. People can always edit the config later on to their desired name.

**Comment by alajmo** [comment]
Should be fixed in 0.20.0, if the issue persists, please open up another ticket.
