### ISSUE TITLE
external variables to "mani run" stmt

### ISSUE THREAD

**Issue by abrahamvc** [alajmo/mani#38]
**Is your feature request related to a problem? Please describe.**

We separated our main repo in 3 different repo with custom use: 

1. Pipeline definition
2. Jobs
3. Tables definitions

Today, we need to move between repos for create a complex process.

```cd repo1
 git checkout -b feature/my_new_feature_A
 ... # more git commands - git diff, add, commit, push
 cd ..

cd repo2
git checkout -b feature/my_new_feature_A
... # more git commands  - git diff, add, commit, push
cd ...

cd repo3
git checkout -b feature/my_new_feature_A
... # more git commands  - git diff, add, commit, push
cd ...
```
That's it the worst case (add a new feature). 

I tried to use "env", but we need to use dynamic variables (for branch names... for example). 

**Describe the solution you'd like**

Something like:

in yaml:
```tasks:
    new-branch:
        cmd: git checkout -b ${branch_name}
        env:
            branch_name: $1
```
`mani run new-branch -a feature/my_new_feature_A`  or something similar. 

**Additional context**
I saw similar projects, but all of them has sync/bulk commands. (see status for every repo, pull changes, see last_commits per repo). In this case, I'm searching for a method to work with multiple repos and manage their life-cycles

Sorry for broken english. Good repo!

**Comment by alajmo** [comment]
Hi, that's already possible, 

```yaml
tasks:
  test:
    desc: simple test task
    cmd: echo "$branch_name"
    env:
      branch_name: main
```

```bash
~/projects/mani/test/playground $ mani run test -a -o table

 Project            | Test
--------------------+------
 playground         | main
 dashgrid           | main
 tap-report         | main
 template-generator | main

~/projects/mani/test/playground $ mani run test -a -o table branch_name=dev

 Project            | Test
--------------------+------
 playground         | dev
 dashgrid           | dev
 tap-report         | dev
 template-generator | dev
```

Though it seems it was undocumented, so thanks for reporting!

**Comment by abrahamvc** [comment]
Ohh! you're right!.

 Thanks!!
