### ISSUE TITLE
Option to disable "Running" output

### ISSUE THREAD

**Issue by tbnguyen1407** [alajmo/mani#44]
## Is your feature request related to a problem? Please describe

Currently writing mani output to file will include the "Running" progress status

## Describe the solution you'd like

Add a flag to silent the output (-s, --silent) which skips extra progress report.

## Additional context

![mani-running](https://user-images.githubusercontent.com/2490928/184065628-3460dc45-6ae9-4696-9a85-3ea93a81dfb8.png)

**Comment by alajmo** [comment]
Sounds like a good idea, I'll add it.

**Comment by alajmo** [comment]
Will be released today as v0.22.0.
