### ISSUE TITLE
Add --tags feature for `mani sync`

### ISSUE THREAD

**Issue by mikeboiko** [alajmo/mani#46]
## Is your feature request related to a problem? Please describe
I only want to sync certain repos on certain machines. Currently, `mani sync` only has the option to clone my repos.

## Describe the solution you'd like
I want to be able to clone a sub-set of my repos, such as: `mani sync --tags main`

## Additional context
The same should probably apply to --paths and --projects as well.

Thanks!

**Comment by alajmo** [comment]
I like this feature, should be easy to implement.

**Comment by alajmo** [comment]
Will be released today as v0.22.0.

**Comment by mikeboiko** [comment]
Awesome, thank you! I'll test it out as soon as it gets updated in the AUR

**Comment by mikeboiko** [comment]
I just tested the feature and it works great. Thanks again!
