### ISSUE TITLE
Don't block mani operation for existing repos, when a target repo doesn't exist

### ISSUE THREAD

**Issue by mikeboiko** [alajmo/mani#59]
## Is your feature request related to a problem? Please describe
If I run a mani operation and one of the target repos doesn't exist, I get an error as such:
```
╭─mike@asus ~
╰─➤  mani run git-status --all
error: path `/home/mike/testrepo1` does not exist
```

## Describe the solution you'd like
I would prefer for this to be a warning instead of an error and have the mani operation complete successfully for the repos that do exist.

## Additional context
I love mani and all the great work you're doing!

**Comment by alajmo** [comment]
Thanks for the suggestion, I added a flag/spec `--ignore-non-existing` / `ignore_non_existing` which you can add for a task or have it be default by providing a `default` spec.

https://github.com/alajmo/mani/releases/tag/v0.23.0

**Comment by mikeboiko** [comment]
That's perfect, thank you!!!
