### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by fabiangeisler** [alajmo/mani#61]
Hi there!

## Is your feature request related to a problem? Please describe
I was wondering if it is possible to bring to `mani` to Windows?!

## Describe the solution you'd like
An extra Windows installer on each GitHub release.

## Additional context
Great project! 🙂

**Comment by fabiangeisler** [comment]
Ok after some tinkering around I was able to create an executable with Go on Windows. Is there anything I should know about? Any known issues with it? 🙂

**Comment by peternepp** [comment]
There are Windows builds as far I can see:

https://github.com/alajmo/mani/releases/download/v0.23.0/mani_0.23.0_windows_amd64.zip

You need to select "Show all assets" on the 0.23.0 release page to get the full list.

**Comment by alajmo** [comment]
It should work out of the box with Windows but please report any errors you encounter. And like @peternepp said, you have to expand the list in the release page (baffled me as well, though I'd forgotten to add the Windows package :P).
Once mani becomes a bit more stable (I have a bunch of features to implement), I'll add it to common windows package repositories for easier install.

**Comment by fabiangeisler** [comment]
Thanks both! 
I guess this is a non issue then. Will report all issues I can find! 🙂
