### ISSUE TITLE
connected-light theme for table

### ISSUE THREAD

**Issue by tbnguyen1407** [alajmo/mani#64]
## Is your feature request related to a problem? Please describe

Add `connected-light` theme for `table` output. Currently this theme is only available for `tree` output.

## Describe the solution you'd like

```
~ mani.yaml ~
themes.default.table.style: connected-light
```

**Comment by alajmo** [comment]
New release that supports the following styles:

- table: light, bold, double, rounded, ascii
- tree: light, bold, ascii, bullet-square, bullet-circle, bullet-star

**Comment by tbnguyen1407** [comment]
Thanks.
