### ISSUE TITLE
Define how many parallel processes gets used

### ISSUE THREAD

**Issue by MindTooth** [alajmo/mani#74]
## Is your feature request related to a problem? Please describe

Setting [`ControlMaster`](https://man.openbsd.org/ssh_config#ControlMaster) throws an error when `mani` creates to many processes:
```
mux_client_request_session: session request failed: Session open refused by peer
ControlSocket /tmp/git@<url>:22 already exists, disabling multiplexing
```

Being able to limit somehow would be nice.

## Describe the solution you'd like

Add the possibility to set how many parallel processes created when invoking `--parallel`.

**Comment by alajmo** [comment]
Fixed with 0.30.0. You can set forks when running tasks (`--parallel --forks=8`) or set it via a spec:

```yaml
specs:
  default:
    parallel: true
    forks: 8
```

It's not set to 4 by default.
