### ISSUE TITLE
Allow hiding empty columns

### ISSUE THREAD

**Issue by tbnguyen1407** [alajmo/mani#76]
## Is your feature request related to a problem? Please describe

Currently there is no option for hide empty columns in table format.

## Describe the solution you'd like

Config to hide empty columns in table format

**Comment by alajmo** [comment]
There's some work left to be done on `sake` before I can bring back changes to `mani` (which includes this feature). Though, not sure about the timeline when I'll be able to do this.

**Comment by alajmo** [comment]
You can now omit empty rows/columns by adding flags `--omit-empty-rows/--omit-empty-columns` or via `specs`.
