### ISSUE TITLE
Mani init fails when CWD is a git repository

### ISSUE THREAD

**Issue by mrjk** [alajmo/mani#78]
- [ ] I have the latest version of mani
- [x] I have searched through the existing issues

## Info

- OS
  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] other

- Shell
  - [x] Bash
  - [ ] Zsh
  - [ ] Fish
  - [ ] Powershell
  - [ ] other

- Version:

```
Version: 0.23.0    
Commit: 83b2ffb   
Date: 2022-12-31T11:24:08Z
```

## Problem / Steps to reproduce

Let's assume test_dir is a dir with a lots of git repos. Let's assume we want test_dir  to be a git repository itself, with a nice README.md explaining how to checkout included repos:
```
cd test_dir
git init .
mani init
error: exit status 1
```
You can't init many, it returns an error.

Workaround: Move temporarly the .git folder to TMP_GIT, do the mani init and rename TMP_GIT to .git again.

**Comment by alajmo** [comment]
Should be fixed with 0.30.0.
