### ISSUE TITLE
Avoid .gitignore rewrite

### ISSUE THREAD

**Issue by ascheman** [alajmo/mani#87]
## Is your feature request related to a problem? Please describe

I already have a well formed .gitignore in my root directory. 
Nevertheless, `mani sync` adds it's own stuff to the .gitgnore file.

## Describe the solution you'd like

I would like to be able to switch off (by default) the changes to the .gitignore, e.g. by adding an entry to the configuration file like `adjust_gitignore` (setting it to `false`, having `true` as the default).

**Comment by alajmo** [comment]
Good idea, will add it to the upcoming release.

**Comment by alajmo** [comment]
Added as of 0.30.0, you can either specify it via the config `sync_gitignore: false` or via a flag when syncing `--sync_gitignore`.
