### ISSUE TITLE
Unable to disable color output

### ISSUE THREAD

**Issue by tbnguyen1407** [alajmo/mani#89]
- [x] I have the latest version of mani
- [x] I have searched through the existing issues

## Info

- OS
  - [ ] Linux
  - [ ] Mac OS X
  - [x] Windows
  - [ ] other

- Shell
  - [x] Bash
  - [ ] Zsh
  - [ ] Fish
  - [ ] Powershell
  - [ ] other

- Version: 0.30.0

## Problem / Steps to reproduce

Unable to disable colors in output. Tried:

```
$ mani run mytask                     ## has colors by default
$ mani run mytask --color false       ## error: cannot find tasks `false`
$ mani run mytask --color no          ## error: cannot find tasks `no`
$ mani run mytask --no-color          ## error: unknown flag: --no-color
```

**Comment by alajmo** [comment]
Has to be `--color=false`, otherwise it's treated as argument.

**Comment by tbnguyen1407** [comment]
Got it. Thanks.
